[workspace]
resolver = "2"
members = [
    "vcore",
    "vemu",
    "vasm_core",
    "vasm",
    "vtest",
    "vlua",
    "vweb",
    "vgfx",
    "forge_core",
    "novaforth"]

[profile.test]
debug-assertions = false
