[package]
name = "vulcan-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
winit = "0.26.1"
pixels = "0.9.0"