pub mod declaration;
mod global;
mod r#const;
mod function;
mod function_prototype;
mod statement;
mod asm;
mod r#return;
mod assignment;
mod var_decl;
mod block;
mod conditional;
mod test_utils;
mod while_loop;
mod repeat_loop;
mod program;
mod operator;
mod expr;